version: "3"
services:
  db:
    container_name: cmtpostgres
    image: postgres:latest
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=car-maintenance-tracker
    ports:
      - '5432:5432'
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  go-backend:
    container_name: gobackend
    build:
      context: ./go-backend
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - db
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - go-backend
      - db
